-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module GraphCool.Subscription exposing (..)

import GraphCool.InputObject
import GraphCool.Interface
import GraphCool.Object
import GraphCool.Scalar
import GraphCool.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.Operation exposing (RootSubscription)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


{-| Select fields to build up a top-level mutation. The request can be sent with
functions from `Graphqelm.Http`.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) RootSubscription
selection constructor =
    Object.selection constructor


{-|

  - filter -

-}
chat : ({ filter : OptionalArgument GraphCool.InputObject.ChatSubscriptionFilter } -> { filter : OptionalArgument GraphCool.InputObject.ChatSubscriptionFilter }) -> SelectionSet decodesTo GraphCool.Object.ChatSubscriptionPayload -> Field (Maybe decodesTo) RootSubscription
chat fillInOptionals object =
    let
        filledInOptionals =
            fillInOptionals { filter = Absent }

        optionalArgs =
            [ Argument.optional "filter" filledInOptionals.filter GraphCool.InputObject.encodeChatSubscriptionFilter ]
                |> List.filterMap identity
    in
    Object.selectionField "Chat" optionalArgs object (identity >> Decode.maybe)


{-|

  - filter -

-}
event : ({ filter : OptionalArgument GraphCool.InputObject.EventSubscriptionFilter } -> { filter : OptionalArgument GraphCool.InputObject.EventSubscriptionFilter }) -> SelectionSet decodesTo GraphCool.Object.EventSubscriptionPayload -> Field (Maybe decodesTo) RootSubscription
event fillInOptionals object =
    let
        filledInOptionals =
            fillInOptionals { filter = Absent }

        optionalArgs =
            [ Argument.optional "filter" filledInOptionals.filter GraphCool.InputObject.encodeEventSubscriptionFilter ]
                |> List.filterMap identity
    in
    Object.selectionField "Event" optionalArgs object (identity >> Decode.maybe)


{-|

  - filter -

-}
file : ({ filter : OptionalArgument GraphCool.InputObject.FileSubscriptionFilter } -> { filter : OptionalArgument GraphCool.InputObject.FileSubscriptionFilter }) -> SelectionSet decodesTo GraphCool.Object.FileSubscriptionPayload -> Field (Maybe decodesTo) RootSubscription
file fillInOptionals object =
    let
        filledInOptionals =
            fillInOptionals { filter = Absent }

        optionalArgs =
            [ Argument.optional "filter" filledInOptionals.filter GraphCool.InputObject.encodeFileSubscriptionFilter ]
                |> List.filterMap identity
    in
    Object.selectionField "File" optionalArgs object (identity >> Decode.maybe)


{-|

  - filter -

-}
host : ({ filter : OptionalArgument GraphCool.InputObject.HostSubscriptionFilter } -> { filter : OptionalArgument GraphCool.InputObject.HostSubscriptionFilter }) -> SelectionSet decodesTo GraphCool.Object.HostSubscriptionPayload -> Field (Maybe decodesTo) RootSubscription
host fillInOptionals object =
    let
        filledInOptionals =
            fillInOptionals { filter = Absent }

        optionalArgs =
            [ Argument.optional "filter" filledInOptionals.filter GraphCool.InputObject.encodeHostSubscriptionFilter ]
                |> List.filterMap identity
    in
    Object.selectionField "Host" optionalArgs object (identity >> Decode.maybe)


{-|

  - filter -

-}
location : ({ filter : OptionalArgument GraphCool.InputObject.LocationSubscriptionFilter } -> { filter : OptionalArgument GraphCool.InputObject.LocationSubscriptionFilter }) -> SelectionSet decodesTo GraphCool.Object.LocationSubscriptionPayload -> Field (Maybe decodesTo) RootSubscription
location fillInOptionals object =
    let
        filledInOptionals =
            fillInOptionals { filter = Absent }

        optionalArgs =
            [ Argument.optional "filter" filledInOptionals.filter GraphCool.InputObject.encodeLocationSubscriptionFilter ]
                |> List.filterMap identity
    in
    Object.selectionField "Location" optionalArgs object (identity >> Decode.maybe)


{-|

  - filter -

-}
message : ({ filter : OptionalArgument GraphCool.InputObject.MessageSubscriptionFilter } -> { filter : OptionalArgument GraphCool.InputObject.MessageSubscriptionFilter }) -> SelectionSet decodesTo GraphCool.Object.MessageSubscriptionPayload -> Field (Maybe decodesTo) RootSubscription
message fillInOptionals object =
    let
        filledInOptionals =
            fillInOptionals { filter = Absent }

        optionalArgs =
            [ Argument.optional "filter" filledInOptionals.filter GraphCool.InputObject.encodeMessageSubscriptionFilter ]
                |> List.filterMap identity
    in
    Object.selectionField "Message" optionalArgs object (identity >> Decode.maybe)


{-|

  - filter -

-}
user : ({ filter : OptionalArgument GraphCool.InputObject.UserSubscriptionFilter } -> { filter : OptionalArgument GraphCool.InputObject.UserSubscriptionFilter }) -> SelectionSet decodesTo GraphCool.Object.UserSubscriptionPayload -> Field (Maybe decodesTo) RootSubscription
user fillInOptionals object =
    let
        filledInOptionals =
            fillInOptionals { filter = Absent }

        optionalArgs =
            [ Argument.optional "filter" filledInOptionals.filter GraphCool.InputObject.encodeUserSubscriptionFilter ]
                |> List.filterMap identity
    in
    Object.selectionField "User" optionalArgs object (identity >> Decode.maybe)


{-|

  - filter -

-}
venue : ({ filter : OptionalArgument GraphCool.InputObject.VenueSubscriptionFilter } -> { filter : OptionalArgument GraphCool.InputObject.VenueSubscriptionFilter }) -> SelectionSet decodesTo GraphCool.Object.VenueSubscriptionPayload -> Field (Maybe decodesTo) RootSubscription
venue fillInOptionals object =
    let
        filledInOptionals =
            fillInOptionals { filter = Absent }

        optionalArgs =
            [ Argument.optional "filter" filledInOptionals.filter GraphCool.InputObject.encodeVenueSubscriptionFilter ]
                |> List.filterMap identity
    in
    Object.selectionField "Venue" optionalArgs object (identity >> Decode.maybe)
