-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module GraphCool.Object.VenuePreviousValues exposing (..)

import GraphCool.InputObject
import GraphCool.Interface
import GraphCool.Object
import GraphCool.Scalar
import GraphCool.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) GraphCool.Object.VenuePreviousValues
selection constructor =
    Object.selection constructor


createdAt : Field GraphCool.Scalar.DateTime GraphCool.Object.VenuePreviousValues
createdAt =
    Object.fieldDecoder "createdAt" [] (Decode.string |> Decode.map GraphCool.Scalar.DateTime)


description : Field (Maybe String) GraphCool.Object.VenuePreviousValues
description =
    Object.fieldDecoder "description" [] (Decode.string |> Decode.maybe)


id : Field GraphCool.Scalar.Id GraphCool.Object.VenuePreviousValues
id =
    Object.fieldDecoder "id" [] (Decode.string |> Decode.map GraphCool.Scalar.Id)


name : Field String GraphCool.Object.VenuePreviousValues
name =
    Object.fieldDecoder "name" [] Decode.string


nameFull : Field String GraphCool.Object.VenuePreviousValues
nameFull =
    Object.fieldDecoder "nameFull" [] Decode.string
