-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module GraphCool.Object exposing (..)


type AddToAttendingEventPayload
    = AddToAttendingEventPayload


type AddToChatInitByPayload
    = AddToChatInitByPayload


type AddToChatPassedPayload
    = AddToChatPassedPayload


type AddToChatProposedPayload
    = AddToChatProposedPayload


type AddToDateCanceledPayload
    = AddToDateCanceledPayload


type AddToEventCreatorPayload
    = AddToEventCreatorPayload


type AddToHostOfEventPayload
    = AddToHostOfEventPayload


type AddToHostOfVenuePayload
    = AddToHostOfVenuePayload


type AddToLikedEventPayload
    = AddToLikedEventPayload


type AddToMessageFromUserPayload
    = AddToMessageFromUserPayload


type AddToMessageOfChatPayload
    = AddToMessageOfChatPayload


type AddToPoolOnChatPayload
    = AddToPoolOnChatPayload


type AddToPoolOnUserPayload
    = AddToPoolOnUserPayload


type AddToRecipientOfChatPayload
    = AddToRecipientOfChatPayload


type AddToUserIsHostPayload
    = AddToUserIsHostPayload


type AddToVenueOfEventPayload
    = AddToVenueOfEventPayload


type Chat
    = Chat


type ChatPreviousValues
    = ChatPreviousValues


type ChatSubscriptionPayload
    = ChatSubscriptionPayload


type Event
    = Event


type EventPreviousValues
    = EventPreviousValues


type EventSubscriptionPayload
    = EventSubscriptionPayload


type File
    = File


type FilePreviousValues
    = FilePreviousValues


type FileSubscriptionPayload
    = FileSubscriptionPayload


type Host
    = Host


type HostPreviousValues
    = HostPreviousValues


type HostSubscriptionPayload
    = HostSubscriptionPayload


type Location
    = Location


type LocationPreviousValues
    = LocationPreviousValues


type LocationSubscriptionPayload
    = LocationSubscriptionPayload


type Message
    = Message


type MessagePreviousValues
    = MessagePreviousValues


type MessageSubscriptionPayload
    = MessageSubscriptionPayload


type Pool
    = Pool


type PoolPreviousValues
    = PoolPreviousValues


type PoolSubscriptionPayload
    = PoolSubscriptionPayload


type QueryMeta_
    = QueryMeta_


type RemoveFromAttendingEventPayload
    = RemoveFromAttendingEventPayload


type RemoveFromChatPassedPayload
    = RemoveFromChatPassedPayload


type RemoveFromChatProposedPayload
    = RemoveFromChatProposedPayload


type RemoveFromDateCanceledPayload
    = RemoveFromDateCanceledPayload


type RemoveFromHostOfEventPayload
    = RemoveFromHostOfEventPayload


type RemoveFromHostOfVenuePayload
    = RemoveFromHostOfVenuePayload


type RemoveFromLikedEventPayload
    = RemoveFromLikedEventPayload


type RemoveFromMessageFromUserPayload
    = RemoveFromMessageFromUserPayload


type RemoveFromPoolOnUserPayload
    = RemoveFromPoolOnUserPayload


type RemoveFromUserIsHostPayload
    = RemoveFromUserIsHostPayload


type RemoveFromVenueOfEventPayload
    = RemoveFromVenueOfEventPayload


type SetEventOnPoolPayload
    = SetEventOnPoolPayload


type SetVenueOnLocationPayload
    = SetVenueOnLocationPayload


type SigninPayload
    = SigninPayload


type UnsetVenueOnLocationPayload
    = UnsetVenueOnLocationPayload


type User
    = User


type UserPreviousValues
    = UserPreviousValues


type UserSubscriptionPayload
    = UserSubscriptionPayload


type Venue
    = Venue


type VenuePreviousValues
    = VenuePreviousValues


type VenueSubscriptionPayload
    = VenueSubscriptionPayload
