-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module GraphCool.Object.UserSubscriptionPayload exposing (..)

import GraphCool.Enum.ModelMutationType_
import GraphCool.Object
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) GraphCool.Object.UserSubscriptionPayload
selection constructor =
    Object.selection constructor


mutation : Field GraphCool.Enum.ModelMutationType_.ModelMutationType_ GraphCool.Object.UserSubscriptionPayload
mutation =
    Object.fieldDecoder "mutation" [] GraphCool.Enum.ModelMutationType_.decoder


node : SelectionSet decodesTo GraphCool.Object.User -> Field (Maybe decodesTo) GraphCool.Object.UserSubscriptionPayload
node object =
    Object.selectionField "node" [] object (identity >> Decode.nullable)


updatedFields : Field (Maybe (List String)) GraphCool.Object.UserSubscriptionPayload
updatedFields =
    Object.fieldDecoder "updatedFields" [] (Decode.string |> Decode.list |> Decode.nullable)


previousValues : SelectionSet decodesTo GraphCool.Object.UserPreviousValues -> Field (Maybe decodesTo) GraphCool.Object.UserSubscriptionPayload
previousValues object =
    Object.selectionField "previousValues" [] object (identity >> Decode.nullable)
