-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module GraphCool.Object.VenueSubscriptionPayload exposing (..)

import GraphCool.Enum.ModelMutationType_
import GraphCool.InputObject
import GraphCool.Interface
import GraphCool.Object
import GraphCool.Scalar
import GraphCool.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) GraphCool.Object.VenueSubscriptionPayload
selection constructor =
    Object.selection constructor


mutation : Field GraphCool.Enum.ModelMutationType_.ModelMutationType_ GraphCool.Object.VenueSubscriptionPayload
mutation =
    Object.fieldDecoder "mutation" [] GraphCool.Enum.ModelMutationType_.decoder


node : SelectionSet decodesTo GraphCool.Object.Venue -> Field (Maybe decodesTo) GraphCool.Object.VenueSubscriptionPayload
node object =
    Object.selectionField "node" [] object (identity >> Decode.nullable)


updatedFields : Field (Maybe (List String)) GraphCool.Object.VenueSubscriptionPayload
updatedFields =
    Object.fieldDecoder "updatedFields" [] (Decode.string |> Decode.list |> Decode.nullable)


previousValues : SelectionSet decodesTo GraphCool.Object.VenuePreviousValues -> Field (Maybe decodesTo) GraphCool.Object.VenueSubscriptionPayload
previousValues object =
    Object.selectionField "previousValues" [] object (identity >> Decode.nullable)
