-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module PlusOne.Object.AddToLikedEventPayload exposing (..)

import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PlusOne.InputObject
import PlusOne.Interface
import PlusOne.Object
import PlusOne.Scalar
import PlusOne.Union


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) PlusOne.Object.AddToLikedEventPayload
selection constructor =
    Object.selection constructor


usersLikedUser : SelectionSet decodesTo PlusOne.Object.User -> Field (Maybe decodesTo) PlusOne.Object.AddToLikedEventPayload
usersLikedUser object =
    Object.selectionField "usersLikedUser" [] object (identity >> Decode.maybe)


eventsLikedEvent : SelectionSet decodesTo PlusOne.Object.Event -> Field (Maybe decodesTo) PlusOne.Object.AddToLikedEventPayload
eventsLikedEvent object =
    Object.selectionField "eventsLikedEvent" [] object (identity >> Decode.maybe)
