-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module PlusOne.Object.RemoveFromDateCanceledPayload exposing (..)

import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PlusOne.InputObject
import PlusOne.Interface
import PlusOne.Object
import PlusOne.Scalar
import PlusOne.Union


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) PlusOne.Object.RemoveFromDateCanceledPayload
selection constructor =
    Object.selection constructor


datesCanceledChat : SelectionSet decodesTo PlusOne.Object.Chat -> Field (Maybe decodesTo) PlusOne.Object.RemoveFromDateCanceledPayload
datesCanceledChat object =
    Object.selectionField "datesCanceledChat" [] object (identity >> Decode.maybe)


canceledUser : SelectionSet decodesTo PlusOne.Object.User -> Field (Maybe decodesTo) PlusOne.Object.RemoveFromDateCanceledPayload
canceledUser object =
    Object.selectionField "canceledUser" [] object (identity >> Decode.maybe)
