-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module PlusOne.Object.RemoveFromHostOfVenuePayload exposing (..)

import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PlusOne.InputObject
import PlusOne.Interface
import PlusOne.Object
import PlusOne.Scalar
import PlusOne.Union


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) PlusOne.Object.RemoveFromHostOfVenuePayload
selection constructor =
    Object.selection constructor


hostsHost : SelectionSet decodesTo PlusOne.Object.Host -> Field (Maybe decodesTo) PlusOne.Object.RemoveFromHostOfVenuePayload
hostsHost object =
    Object.selectionField "hostsHost" [] object (identity >> Decode.maybe)


venuesVenue : SelectionSet decodesTo PlusOne.Object.Venue -> Field (Maybe decodesTo) PlusOne.Object.RemoveFromHostOfVenuePayload
venuesVenue object =
    Object.selectionField "venuesVenue" [] object (identity >> Decode.maybe)
