-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module PlusOne.Object.UserPreviousValues exposing (..)

import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PlusOne.InputObject
import PlusOne.Interface
import PlusOne.Object
import PlusOne.Scalar
import PlusOne.Union


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) PlusOne.Object.UserPreviousValues
selection constructor =
    Object.selection constructor


auth0UserId : Field (Maybe String) PlusOne.Object.UserPreviousValues
auth0UserId =
    Object.fieldDecoder "auth0UserId" [] (Decode.string |> Decode.maybe)


bio : Field (Maybe String) PlusOne.Object.UserPreviousValues
bio =
    Object.fieldDecoder "bio" [] (Decode.string |> Decode.maybe)


birthday : Field PlusOne.Scalar.DateTime PlusOne.Object.UserPreviousValues
birthday =
    Object.fieldDecoder "birthday" [] (Decode.string |> Decode.map PlusOne.Scalar.DateTime)


createdAt : Field PlusOne.Scalar.DateTime PlusOne.Object.UserPreviousValues
createdAt =
    Object.fieldDecoder "createdAt" [] (Decode.string |> Decode.map PlusOne.Scalar.DateTime)


email : Field (Maybe String) PlusOne.Object.UserPreviousValues
email =
    Object.fieldDecoder "email" [] (Decode.string |> Decode.maybe)


id : Field PlusOne.Scalar.Id PlusOne.Object.UserPreviousValues
id =
    Object.fieldDecoder "id" [] (Decode.string |> Decode.map PlusOne.Scalar.Id)


name : Field String PlusOne.Object.UserPreviousValues
name =
    Object.fieldDecoder "name" [] Decode.string


nameFull : Field (Maybe String) PlusOne.Object.UserPreviousValues
nameFull =
    Object.fieldDecoder "nameFull" [] (Decode.string |> Decode.maybe)


password : Field (Maybe String) PlusOne.Object.UserPreviousValues
password =
    Object.fieldDecoder "password" [] (Decode.string |> Decode.maybe)


updatedAt : Field PlusOne.Scalar.DateTime PlusOne.Object.UserPreviousValues
updatedAt =
    Object.fieldDecoder "updatedAt" [] (Decode.string |> Decode.map PlusOne.Scalar.DateTime)
