-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module PlusOne.Enum.EventOrderBy exposing (..)

import Json.Decode as Decode exposing (Decoder)


type EventOrderBy
    = CreatedAt_ASC
    | CreatedAt_DESC
    | EndsAt_ASC
    | EndsAt_DESC
    | Id_ASC
    | Id_DESC
    | Name_ASC
    | Name_DESC
    | NameFull_ASC
    | NameFull_DESC
    | Private_ASC
    | Private_DESC
    | StartsAt_ASC
    | StartsAt_DESC


decoder : Decoder EventOrderBy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "endsAt_ASC" ->
                        Decode.succeed EndsAt_ASC

                    "endsAt_DESC" ->
                        Decode.succeed EndsAt_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "name_ASC" ->
                        Decode.succeed Name_ASC

                    "name_DESC" ->
                        Decode.succeed Name_DESC

                    "nameFull_ASC" ->
                        Decode.succeed NameFull_ASC

                    "nameFull_DESC" ->
                        Decode.succeed NameFull_DESC

                    "private_ASC" ->
                        Decode.succeed Private_ASC

                    "private_DESC" ->
                        Decode.succeed Private_DESC

                    "startsAt_ASC" ->
                        Decode.succeed StartsAt_ASC

                    "startsAt_DESC" ->
                        Decode.succeed StartsAt_DESC

                    _ ->
                        Decode.fail ("Invalid EventOrderBy type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : EventOrderBy -> String
toString enum =
    case enum of
        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        EndsAt_ASC ->
            "endsAt_ASC"

        EndsAt_DESC ->
            "endsAt_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        Name_ASC ->
            "name_ASC"

        Name_DESC ->
            "name_DESC"

        NameFull_ASC ->
            "nameFull_ASC"

        NameFull_DESC ->
            "nameFull_DESC"

        Private_ASC ->
            "private_ASC"

        Private_DESC ->
            "private_DESC"

        StartsAt_ASC ->
            "startsAt_ASC"

        StartsAt_DESC ->
            "startsAt_DESC"
