-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module PlusOne.Enum.HostOrderBy exposing (..)

import Json.Decode as Decode exposing (Decoder)


type HostOrderBy
    = CreatedAt_ASC
    | CreatedAt_DESC
    | Description_ASC
    | Description_DESC
    | Id_ASC
    | Id_DESC
    | Name_ASC
    | Name_DESC
    | NameFull_ASC
    | NameFull_DESC


decoder : Decoder HostOrderBy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "description_ASC" ->
                        Decode.succeed Description_ASC

                    "description_DESC" ->
                        Decode.succeed Description_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "name_ASC" ->
                        Decode.succeed Name_ASC

                    "name_DESC" ->
                        Decode.succeed Name_DESC

                    "nameFull_ASC" ->
                        Decode.succeed NameFull_ASC

                    "nameFull_DESC" ->
                        Decode.succeed NameFull_DESC

                    _ ->
                        Decode.fail ("Invalid HostOrderBy type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : HostOrderBy -> String
toString enum =
    case enum of
        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        Description_ASC ->
            "description_ASC"

        Description_DESC ->
            "description_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        Name_ASC ->
            "name_ASC"

        Name_DESC ->
            "name_DESC"

        NameFull_ASC ->
            "nameFull_ASC"

        NameFull_DESC ->
            "nameFull_DESC"
