-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module GraphCool.Object.FilePreviousValues exposing (..)

import GraphCool.InputObject
import GraphCool.Interface
import GraphCool.Object
import GraphCool.Scalar
import GraphCool.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) GraphCool.Object.FilePreviousValues
selection constructor =
    Object.selection constructor


contentType : Field String GraphCool.Object.FilePreviousValues
contentType =
    Object.fieldDecoder "contentType" [] Decode.string


createdAt : Field GraphCool.Scalar.DateTime GraphCool.Object.FilePreviousValues
createdAt =
    Object.fieldDecoder "createdAt" [] (Decode.string |> Decode.map GraphCool.Scalar.DateTime)


id : Field GraphCool.Scalar.Id GraphCool.Object.FilePreviousValues
id =
    Object.fieldDecoder "id" [] (Decode.string |> Decode.map GraphCool.Scalar.Id)


name : Field String GraphCool.Object.FilePreviousValues
name =
    Object.fieldDecoder "name" [] Decode.string


secret : Field String GraphCool.Object.FilePreviousValues
secret =
    Object.fieldDecoder "secret" [] Decode.string


size : Field Int GraphCool.Object.FilePreviousValues
size =
    Object.fieldDecoder "size" [] Decode.int


updatedAt : Field GraphCool.Scalar.DateTime GraphCool.Object.FilePreviousValues
updatedAt =
    Object.fieldDecoder "updatedAt" [] (Decode.string |> Decode.map GraphCool.Scalar.DateTime)


url : Field String GraphCool.Object.FilePreviousValues
url =
    Object.fieldDecoder "url" [] Decode.string
